/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Metodos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Padilla
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreDeUsuario = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNick1 = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnRegistro = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        Password = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Registrate = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreDeUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        NombreDeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        NombreDeUsuario.setText("Nombre de Usuario : ");
        getContentPane().add(NombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 270, 30));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 270, 30));

        txtNick1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtNick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 270, 30));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 270, 30));

        btnRegistro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnRegistro.setText("Registrar");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        Password.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Contraseña : ");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        Correo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Correo.setForeground(new java.awt.Color(255, 255, 255));
        Correo.setText("Correo electronico : ");
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        Nombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre y Apellido :");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        Registrate.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Registrate.setForeground(new java.awt.Color(255, 255, 255));
        Registrate.setText("-Registrate-");
        getContentPane().add(Registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9e73482beeb9272405b1392fc9c521b6.png"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu ventana2 = new Menu();
         ventana2.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        ConexionBD.Conectar();
        ConexionBD.EjecutarUpdate("INSERT INTO USUARIO VALUES ('"+txtCorreo.getText()+"' , '"+txtNombre.getText()+"' , '"+txtCorreo.getText()+"' , '"+txtPassword.getText()+"')");
        JOptionPane.showMessageDialog(null, "Registro Completado");
        Menu ventana2 = new Menu();
        ventana2.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreDeUsuario;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Registrate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNick1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
